### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by famigone** [perak/meteor-mqtt-collection#10]
I'm ussing Meteor 1.8.3. In the server/main.js i hava this code: 
`**import { Events } from "/imports/api/events.js";

Meteor.startup(() => {
  let server = Meteor.settings.mqttHost;
  Events.mqttConnect(server, ["beaglebone/+"], {}, {});
}**
`

and i get the next error: 
`**packages/perak_mqtt-collection.js:133
	} else if(_.isArray(topics)) {
	       ^

ReferenceError: _ is not defined
    at Collection.Mongo.Collection.mqttSubscribe (packages/perak_mqtt-collection.js:133:9)
    at MqttClient.<anonymous> (packages/perak_mqtt-collection.js:51:8)
    at emitOne (events.js:121:20)
    at MqttClient.emit (events.js:211:7)
    at MqttClient._handleConnack (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/mqtt/lib/client.js:718:10)
    at MqttClient._handlePacket (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/mqtt/lib/client.js:292:12)
    at process (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/mqtt/lib/client.js:234:12)
    at Writable.writable._write (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/mqtt/lib/client.js:244:5)
    at doWrite (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/home/fede/.meteor/packages/perak_mqtt-collection/.1.0.5.xpr8zf.9jns++os+web.browser+web.cordova/npm/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
Exited with code: 1
Your application is crashing. Waiting for file change.`**

The mosquitto server is runing, and i can connect whit it [from this old example](https://github.com/sakulstra/iot-mqtt-test), but not from my new code.

**Comment by perak** [comment]
This package is not maintained, but... by error message I believe that you need to `meteor install underscore` (underscore was included in early versions of meteor by default, but is removed later)

**Comment by famigone** [comment]
All right now, thanks!!!!
