### ISSUE TITLE
Install fails on Ubuntu 16.04 

### ISSUE THREAD

**Issue by njvanbal** [perak/meteor-mqtt-collection#7]
I am trying to add this package to a meteor project on Ubuntu 16.04. Every time I try to add it I get the following error:

```
While loading package perak:mqtt-collection@1.0.4:
   error: Command failed: ~/.meteor/packages/meteor- tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
   In file included from ../src/bufferutil.cc:16:0:
   ../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
   NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
   ^
   ../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
   NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
   ^
   ../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
   , node::smalloc::FreeCallback callback
   ^
   ../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
   , node::smalloc::FreeCallback callback
   ^
   ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
   ../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
   v8::Isolate::GetCurrent(), data, length, callback, hint);
   ^
   ../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
   v8::Isolate::GetCurrent(), data, length, callback, hint);
   ^
   ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
   ../node_modules/nan/nan.h:672:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
   return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
   ^
   In file included from ../src/bufferutil.cc:10:0:
   ~/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
   NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
   ^
  ~/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
   In file included from ../src/bufferutil.cc:16:0:
   ../node_modules/nan/nan.h:672:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
   return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
   ^
   In file included from ../src/bufferutil.cc:10:0:
   ~/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
   NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
   ^
   ~/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
   In file included from ../src/bufferutil.cc:16:0:
   ../node_modules/nan/nan.h:672:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
   ^
   ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
   ../node_modules/nan/nan.h:676:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
   return node::Buffer::New(v8::Isolate::GetCurrent(), size);
   ^
   ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
   ../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
   return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
   ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
   gyp ERR! build error
   gyp ERR! stack Error: `make` failed with exit code: 2
   gyp ERR! stack     at ChildProcess.onExit (~/.meteor/packages/meteor-tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle /lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
   gyp ERR! System Linux 4.4.0-31-generic
   gyp ERR! command "~/.meteor/packages/meteor-tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "~/.meteor/packages/meteor-tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   gyp ERR! cwd ~/.meteor/packages/perak_mqtt-collection/.1.0.4.1lhdxh9++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-16joajv/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Linux 4.4.0-31-generic
   npm ERR! argv "~/.meteor/packages/meteor-tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "~/.meteor/packages/meteor-tool/.1.4.0.oqdg7s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bufferutil package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bufferutil
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bufferutil
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     ~/.meteor/packages/perak_mqtt-collection/.1.0.4.1lhdxh9++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-16joajv/npm-debug.log
```

I have tried installing the npms separately which give me no errors but different versions. I have tried installing on other version of Linux. It does work on Windows, but my target deployment environment is Linux, so that is not an option.
Is there any solution to this error?

**Comment by perak** [comment]
@njvanbal I got the same problem. npm package `bufferutil` is the one which makes troubles. I didn't have enough time to find a solution. If you find something, please let me know.

**Comment by perak** [comment]
BTW, not only ubuntu 16.04 : the same on CentOS 6 and MacOSX

**Comment by njvanbal** [comment]
I ran the package locally and switched the dependency in package.json from mqtt version1.2.0 to mqtt version 1.13.0 and that seems to have fixed the problem.

**Comment by perak** [comment]
@njvanbal thank you! 👍

**Comment by perak** [comment]
I'll fix it ASAP

**Comment by perak** [comment]
@njvanbal OK, fixed. perak:mqtt-collection@1.0.5
